idf_component_register(
    SRCS
        "../../src/ui/ui.c"
        "../../src/ui/ui_channel_detail.c"
        "../../src/ui/ui_graph.c"
        "../../src/ui/ui_main.c"
        "../../src/ui/ui_numpad.c"
        "../../src/ui/ui_keyboard.c"
        "../../src/ui/ui_settings.c"
        "../../src/ui/ui_wireless.c"
        "../../src/ui/ui_ota.c"
        "display.c"
        "touch.c"
        "wireless_controller.c"
        "dc_load_controller.c"
        "web_server.c"
        "main.c"
    INCLUDE_DIRS
        "."
        "../../src"
        "../../src/ui"
    REQUIRES
        esp_lcd
        driver
        nvs_flash
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        app_update
        spiffs
)

spiffs_create_partition_image(spiffs www FLASH_IN_PROJECT)
