M48
; DRILL file {KiCad (6.0.6)} date Mon Jul 25 14:05:36 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-25T14:05:36+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X4.5817Y-3.1969
X4.5817Y-5.1102
X6.7667Y-5.1063
X6.7726Y-3.2028
T0
M30
