; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s2ucp]
platform = espressif32
board = esp32-s2-ucp
framework = arduino
extra_scripts = pre:tools/pre_build.py
board_build.partitions = ucp.csv
lib_compat_mode = strict
lib_deps =
	WiFi
	Update
	FS
	ayushsharma82/ElegantOTA@^3.1.6
	ayushsharma82/ESP-DASH@^4.0.8
  ;lvgl/lvgl@^7.11
  TFT_eSPI@^2.5.43
  ;adafruit/Adafruit FT6206 Library@^1.1.0
build_flags =
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DCONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
    -DCONFIG_ASYNC_TCP_PRIORITY=10
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
    -DCONFIG_ASYNC_TCP_STACK_SIZE=4096
    -I files/include
    ;-DLV_CONF_PATH=../../../../include/lv_conf.h
    ; TFT_eSPI library:
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1                           ; ???
    ;-D TFT_WIDTH=320 -D TFT_HEIGHT=240          ; defined in ILI9341 driver
    -D TFT_MOSI=23 ; orig: 23
    -D TFT_SCLK=18 ;       18
    -D TFT_CS=0    ;       0
    -D TFT_DC=2    ;       2
    -D TFT_RST=13  ;       13
    ;-D SMOOTH_FONT
    ;-D TOUCH_CS=21 ; for testing only
    ;-D SPI_FREQUENCY=25000000
    ;-D SPI_READ_FREQUENCY=20000000
    ;-D SPI_TOUCH_FREQUENCY=2500000
monitor_speed = 921600
monitor_port = COM14
