; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s2ucp]
platform = espressif32
board = esp32-s2-ucp
framework = arduino
extra_scripts = pre:tools/pre_build.py
board_build.partitions = ucp.csv
lib_compat_mode = strict
lib_deps =
	WiFi
	Update
	FS
	ayushsharma82/ElegantOTA@^3.1.6
	ayushsharma82/ESP-DASH@^4.0.8
build_flags =
    -DELEGANTOTA_USE_ASYNC_WEBSERVER=1
    -DCONFIG_ASYNC_TCP_MAX_ACK_TIME=3000
    -DCONFIG_ASYNC_TCP_PRIORITY=10
    -DCONFIG_ASYNC_TCP_QUEUE_SIZE=128
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=1
    -DCONFIG_ASYNC_TCP_STACK_SIZE=4096
    -I files/include
monitor_speed = 921600
monitor_port = COM14
