report:
    pandoc report.md -o report.pdf  --pdf-engine=xelatex -V geometry:margin=1in --number-sections \
    --filter pandoc-crossref --citeproc -V colorlinks=true -V linkcolor=red -V citecolor=blue -V urlcolor=red